apiVersion: v1
kind: Service
metadata:
    name: signalrcore-svc
    labels:
       app: signalrcore
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: signalrcore